---
#   Copyright Red Hat, Inc. All Rights Reserved.
#
#   Licensed under the Apache License, Version 2.0 (the "License"); you may
#   not use this file except in compliance with the License. You may obtain
#   a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#   WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#   License for the specific language governing permissions and limitations
#   under the License.
#

- name: Ensure python-virtualenv is installed
  package:
    name: "python-virtualenv"
    state: "present"

# https://github.com/kokosing/docker-release/issues/3
- name: Initialize virtual environment with up-to-date setuptools
  pip:
    name: "setuptools"
    state: "latest"
    virtualenv: "/tmp/kolla-ansible"

- name: Install kolla-ansible
  pip:
    name: "https://github.com/openstack/kolla-ansible.git"
    state: "present"
    virtualenv: "/tmp/kolla-ansible"

# kolla-ansible abstracts the ansible-playbook command with the kolla-ansible
# tool.
# We don't need it's features and we don't want to hide the tasks that are
# run as part of the host bootstrap -- this is why we include the role here
# natively.
- name: Create default Ansible directory
  file:
    path: "/etc/ansible"
    state: "directory"

- name: Setup kolla-ansible roles in the default Ansible role path
  file:
    src: "/etc/ansible/roles"
    dest: "/tmp/kolla-ansible/share/kolla/ansible/roles/"

# Override redhat_pkg_install to prevent epel-release installation
# https://github.com/openstack/kolla-ansible/blob/7f1084808b34cfc32683e4259f88e29fd24e53be/ansible/roles/baremetal/defaults/main.yml#L21
- name: Include kolla-ansible baremetal role (bootstrap-servers)
  vars:
    action: "bootstrap-servers"
    redhat_pkg_install:
      - docker-engine-1.11.0
      - git
      - python-setuptools
      - ntp
  include_role:
    name: "baremetal"
